image: node:11.14.0

# Install lein - required to build the project
before_script:
  - apt-get update -y
  - apt-get install default-jre postgresql-client -y
  - wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
  - chmod a+x lein
  - export LEIN_ROOT=1
  - PATH=$PATH:.
  - lein cljfmt check
  - lein with-profile +dev run &
  - gem install awesome_bot

test:
  script:
    # setup dependencies
    - npm install
    # Build CSS
    - lein less once
    # ensure a minified build completes without error
    - lein cljsbuild once min
    # run UI tests using Cypress
    - npx cypress run
    # build API docs
    - lein codox
    # check for the links in the documentation
    - awesome_bot docs/*.md --allow-dupe --allow-redirect -w localhost
