# Ruby is required for awesome_bot
image: ruby:2.6

# to cache both npm modules and Cypress binary we use environment variables
# to point at the folders we can list as paths in "cache" job settings
variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

# cache using branch name
# https://gitlab.com/help/ci/caching/index.md
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress
    - node_modules

before_script:
  # Java install
  - apt-get update -y
  - apt-get install default-jre -y
  # NPM/node install
  - curl -sL https://deb.nodesource.com/setup_11.x | bash -
  - apt-get install -y nodejs
  # required for cypress tests
  - apt-get install xvfb libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 -y
  # Lein install
  - wget https://raw.githubusercontent.com/technomancy/leiningen/2.8.3/bin/lein
  - chmod a+x lein
  - export LEIN_ROOT=1
  - PATH=$PATH:.
  - lein with-profile +dev run &
  # Link Checker
  - gem install awesome_bot

stages:
  - build
  - test

build:
  stage: build
  script:
    # setup dependencies
    - npm install
    # Build CSS
    - lein less once
    # ensure a minified build completes without error
    - lein cljsbuild once min

ui-testing:
  stage: test
  script:
    # run UI tests using Cypress
    - npm install cypress
    - cypress install
    - npx cypress run
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 day


check-format:
  stage: test
  script:
    # Check formatting
    - lein cljfmt check

docs:
  stage: test
  script:
    # build API docs
    - lein codox
    # check for the links in the documentation
    - awesome_bot docs/*.md --allow-dupe --allow-redirect -w localhost
