# Ruby is required for awesome_bot
image: ruby:2.6

before_script:
  # Java install
  - apt-get update -y
  - apt-get install default-jre -y
  # NPM/node install
  - curl -sL https://deb.nodesource.com/setup_11.x | bash -
  - apt-get install -y nodejs
  # Lein install
  - wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
  - chmod a+x lein
  - export LEIN_ROOT=1
  - PATH=$PATH:.
  - lein with-profile +dev run &
  # Link Checker
  - gem install awesome_bot
  # required for cypress tests
  - apt-get install xvfb libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 -y

stages:
  - build
  - test

build:
  stage: build
  script:
    # setup dependencies
    - npm install
    # Build CSS
    - lein less once
    # ensure a minified build completes without error
    - lein cljsbuild once min

ui-testing:
  stage: test
  script:
    # run UI tests using Cypress
    - npx cypress run
  artifacts:
    paths:
    - cypress/*
    expire_in: 1 week


check-format:
  stage: test
  script:
    # Check formatting
    - lein cljfmt check

docs:
  stage: test
  script:
    # build API docs
    - lein codox
    # check for the links in the documentation
    - awesome_bot docs/*.md --allow-dupe --allow-redirect -w localhost
