language: generic
sudo: required

before_script:
  - wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein -O /tmp/lein
  - chmod +x /tmp/lein
  - export PATH=$PATH:/tmp/lein

script:
  - npm install
  - lein less once
  - lein cljsbuild once min
  - lein codox

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: target/docs
  on:
    branch: dev
