language: java
jdk: openjdk9
sudo: required

# Install lein - required to build the project
before_script:
  - wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein -O /tmp/lein
  - chmod +x /tmp/lein
  - export PATH=$PATH:/tmp/lein
  - lein cljfmt check

script:
  # setup dependencies
  - npm install
  # Build CSS
  - lein with-profile +java9 less once
  # ensure a minified build completes without error
  - lein with-profile +java9 cljsbuild once min
  # build API docs
  - lein with-profile +java9 codox

# Deploys build API docs:
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: target/doc
  on:
    branch: dev
